In [1]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
l=range(1000)
%timeit  [i**2 for i in l]

505 µs ± 176 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
ls=np.arange(1000)
%timeit ls**2

3.96 µs ± 440 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
arr.ndim

1

In [13]:
arr.shape

(5,)

In [14]:
len(arr)

5

In [16]:
arr2=np.array([[2,3,1],[1,0,9]])
arr2

array([[2, 3, 1],
       [1, 0, 9]])

In [18]:

arr2.shape


(2, 3)

## 

In [19]:
arr2.ndim

2

In [20]:
len(arr2)

2

In [21]:
c=np.array([[[1,3,4],[0,9,8]],[[2,7,4],[4,5,6]]])
c

array([[[1, 3, 4],
        [0, 9, 8]],

       [[2, 7, 4],
        [4, 5, 6]]])

In [22]:
c.ndim

3

In [23]:
c.shape

(2, 2, 3)

In [26]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
cd=np.zeros((3,3))
cd

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
c1=np.ones((3,3))
c1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
c2=np.diag((2,4))
c2


array([[2, 0],
       [0, 4]])

In [37]:
np.diag(c2)

array([2, 4])

In [38]:
c4=np.random.rand(5)
c4

array([0.33390589, 0.63440476, 0.12695553, 0.67656517, 0.92278313])

In [41]:
d=np.array((4+3j,2+3j))
print(d.dtype)

complex128


In [42]:
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a[1:8:2]

array([1, 3, 5, 7])

In [45]:
arr

array([1, 2, 3, 4, 5])

In [46]:
arr+1

array([2, 3, 4, 5, 6])

In [47]:
arr*2

array([ 2,  4,  6,  8, 10])

In [49]:
a=np.diag((1,2,3,4))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [50]:
print(a*a)
print("************************")
print(a.dot(a))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [51]:
d=np.array([1,3,5,7])
f=np.array([8,3,0,7])
d==f



array([False,  True, False,  True])

In [52]:
d>f

array([False, False,  True, False])

In [53]:
np.array_equal(d,f)

False

In [54]:
a=np.tile(np.arange(0,40,10),(3,2))
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [56]:
d=a.T
print(d)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
